apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
  labels:
    k8s-app: cluster-hosted-operator
  name: cluster-hosted-net-services-operator
  namespace: cluster-hosted-net-services-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: cluster-hosted-operator
  template:
    metadata:
      annotations:
        include.release.openshift.io/self-managed-high-availability: "true"
      labels:
        k8s-app: cluster-hosted-operator
    spec:
      containers:
      - command:
        - /manager
        env:
        - name: RELEASE_VERSION
          value: 0.0.1-snapshot
        - name: COMPONENT_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: METRICS_PORT
          value: "8080"
        - name: HANDLER_NAMESPACE
          value: cluster-hosted-net-services
        - name: ON_PREM_API_VIP
          value: 192.168.111.99
        - name: ON_PREM_INGRESS_VIP
          value: 192.168.111.88
        - name: DNS_BASE_DOMAIN
          value: test.metalkube.org
        image: quay.io/yboaron/cluster-hosted-ctrl:latest
        name: cluster-hosted-operator
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
        volumeMounts:
        - mountPath: /etc/cluster-hosted-operator/images
          name: images
          readOnly: true
      nodeSelector:
        node-role.kubernetes.io/master: ""
      priorityClassName: system-node-critical
      restartPolicy: Always
      serviceAccountName: cluster-hosted-operator
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        operator: Exists
        tolerationSeconds: 120
      - effect: NoExecute
        key: node.kubernetes.io/not-ready
        operator: Exists
        tolerationSeconds: 120
      volumes:
      - configMap:
          name: cluster-hosted-operator-images
        name: images
