apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
  name: cluster-hosted-operator
  namespace: cluster-hosted-net-services-operator
