apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  name: cluster-hosted
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
spec: {}
status:
  versions:
  - name: operator
    version: "0.0.1-snapshot"
